### PR TITLE
Support content type 45 for AudioEninge/SoundBank/WaveBank

### PR DESCRIPTION
**Pull request by alesliehughes**
Game: Drakensang - The River of Time.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Worth noting that this may also apply to XACT 3.3 - this should be checked with Blazblue Calamity Trigger.

**Comment by alesliehughes** [comment]
Maybe, I currently don't have access to that game, so cant test it directly.

**Comment by flibitijibibo** [comment]
Worst case it just means we have to rename "3_4" to "3_3" for clarity. I've also moved all the version stuff to one spot:

https://github.com/FNA-XNA/FAudio/commit/b5f57cb8787abac9cad612b9c6daacb24e2d98ff

**Comment by alesliehughes** [comment]
Thanks, that look cleaner.

**Pull request merged**
