### PR TITLE
Support 5p1 -> 5p1 reverb

### PR DESCRIPTION
**Pull request by aeikum**
This is required by Rez Infinite, see #225. I'm pretty sure I got all of the places where channel counts are used, but please double-check, and also look over my usage of the internal reverb API.

As always, feel free to fixup any style issues in this commit.

### CODE REVIEW

**Comment by aeikum** [comment]
Force-pushed a fix to averaging the input sample (used to divide by 6, now divides by 5).

**Comment by flibitijibibo** [comment]
I could be misremembering but I believe DspReverb_SetParameters also has an array that assumes a max of 4 channels rather than 5, I think all it needs is an additional entry but it's been a long time since I've looked at this.

**Comment by aeikum** [comment]
Good catch. That also showed me we were accessing past the end of STEREO_SPREAD. I've redone the left/right/rear logic to be based on speaker position flags. I tested how the center channel is treated on Windows with both 2.7 and 2.8, and it seems broken. It seems to behave the same as the left speaker. Instead in this code, I just averaged the left and right values for the center speaker. We already sound significantly different from Windows for the left/right parameters, so if we want to match Windows more closely, we can look into that separately.

**Comment by flibitijibibo** [comment]
That's pretty wild... but yeah we're a million miles off of the Princeton sound, so I'd rather be correct than accurate in this case.

Thanks for checking this out, this looks good!

**Pull request merged**
