### PR TITLE
Use memcpy when we can for mixing

### PR DESCRIPTION
**Pull request by aeikum**
This fixes frequent underruns during cutscenes in Beyond Two Souls on my PC. The game does a ton of 8->8 channel sends with an identity matrix, which we can simply replace with a memcpy. I think we could likely do more improvements in the non-identity case, but I'm not at all familiar with SSE stuff.

### CODE REVIEW

**Comment by aeikum** [comment]
(Pushed a fix to use FAudio_memcpy instead of memcpy.)

**Comment by flibitijibibo** [comment]
This makes sense to me - I wonder if we can offload this to the API side rather than the mixer? My thinking is that we can do the same check when SetOutputVoices/SetVolume/SetChannelVolumes is called, then all the mixer has to do is check for `isIdentityGain` and go straight to memcpy without calling the function pointer at all. Less maintenance on the SIMD side and possibly performs even better in this case?

**Comment by aeikum** [comment]
I was working on that when I noticed an obvious problem - we need to be _mixing into_ these buffers, not overwriting them. So I'm not sure memcpy is an option at all, here.

**Comment by aeikum** [comment]
I'm going to see if I can do this with SSE2 intrinsics. Let me know if you think this is a bad path to go down.

**Comment by flibitijibibo** [comment]
Oh, duh, you're right... memcpy would only work for the first source voice.

If there's a way we can do it with SIMD that's good enough for me. NEON is pretty easy to port over to as well (at least in my experience), I'll just have to dig up an ARM device to test against if someone doesn't beat me to it.

**Pull request closed without merging**
